#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Sep 15 00:03:02 CEST 2026
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim ShiftRegister_tb_behav -key {Behavioral:sim_1:Functional:ShiftRegister_tb} -tclbatch ShiftRegister_tb.tcl -log simulate.log"
xsim ShiftRegister_tb_behav -key {Behavioral:sim_1:Functional:ShiftRegister_tb} -tclbatch ShiftRegister_tb.tcl -log simulate.log

